### PR TITLE
Update drag.js

### PR DESCRIPTION
**Pull request by Glinkis**
Fix whitespace & indentation.

### CODE REVIEW

**Comment by coderitual** [comment]
Hi Glinkis! Thanks for the PR. Your change reminds me this project needs strong refactoring and I would welcome tools like prettier. At least there is a consistency now :)

**Comment by Glinkis** [comment]
Yeah, I could perhaps look at setting up prettier for this project if you'd like.

I would of course configure it to align as close as possible with the current style.

**Comment by Glinkis** [comment]
Although I see now that you don't have a `package.json` file anywhere?

**Comment by coderitual** [comment]
Yup, there is no package.json. Deps are in lib folder. I know this is outdated. Project was created in 2011 :)

**Pull request merged**
